# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
kara-k8s-master1 ansible_host=192.168.5.191   etcd_member_name=etcd1  #ip=10.10.10.100
kara-k8s-master2 ansible_host=192.168.5.193   etcd_member_name=etcd2  #ip=10.10.10.100
kara-k8s-master3 ansible_host=192.168.5.195   etcd_member_name=etcd3  #ip=10.10.10.100

# node1 ansible_host=95.54.0.12  # ip=10.3.0.1 etcd_member_name=etcd1
# node2 ansible_host=95.54.0.13  # ip=10.3.0.2 etcd_member_name=etcd2
# node3 ansible_host=95.54.0.14  # ip=10.3.0.3 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
kara-k8s-worker1 ansible_host=192.168.5.192    #ip=10.10.10.100
kara-k8s-worker2 ansible_host=192.168.5.194    #ip=10.10.10.100
kara-k8s-worker3 ansible_host=192.168.5.196    #ip=10.10.10.100

# node4 ansible_host=95.54.0.15  # ip=10.3.0.4
# node5 ansible_host=95.54.0.16  # ip=10.3.0.5
# node6 ansible_host=95.54.0.17  # ip=10.3.0.6

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
